src/main/java/com/vincedgy/jsf2project/managedBeans/AgenceVoyageBean.java
package com.vincedgy.jsf2project.managedBeans;

import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import com.vincedgy.jsf2project.jaxb.ModeDeTransport;
import com.vincedgy.jsf2project.jaxb.Ville;
import com.vincedgy.jsf2project.services.AgenceVoyagesServiceImpl;

@ManagedBean(name="agenceVoyageBean")
@SessionScoped
public class AgenceVoyageBean implements Serializable {

	private static final long serialVersionUID = 1L;
	
	private AgenceVoyagesServiceImpl agenceVoyagesService = AgenceVoyagesServiceImpl.getInstance();
	private List<Ville> villes; 
	private List<ModeDeTransport> modesDeTransport;
	
	public AgenceVoyageBean() {	}
	
	public List<Ville> getVilles() {
		return villes;
	}

	public List<ModeDeTransport> getModesDeTransport() {
		return modesDeTransport;
	}

	@PostConstruct
	public void init() {
		villes = agenceVoyagesService.getAgenceVoyages().getVille();
		modesDeTransport = agenceVoyagesService.getAgenceVoyages().getModeDeTransport();
	}
		
}

src/main/java/com/vincedgy/jsf2project/managedBeans/LoginBean.java
package com.vincedgy.jsf2project.managedBeans;

import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean(name="loginBean")
@SessionScoped
public class LoginBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private String name="Vincent";
	private String password;

	public LoginBean() {}
	
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

}

src/main/java/com/vincedgy/jsf2project/managedBeans/ProjectFormBean.java
package com.vincedgy.jsf2project.managedBeans;

import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

@ManagedBean(name="projectFormBean")
@RequestScoped
public class ProjectFormBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private String projectName;
	private String projectDescription;
	
	public ProjectFormBean() {}
	
	public String getProjectName() {
		return projectName;
	}
	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}
	public String getProjectDescription() {
		return projectDescription;
	}
	public void setProjectDescription(String projectDescription) {
		this.projectDescription = projectDescription;
	}
	
	
	

}

src/main/java/com/vincedgy/jsf2project/managedBeans/TrajetBean.java
package com.vincedgy.jsf2project.managedBeans;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;

import com.vincedgy.jsf2project.jaxb.ModeDeTransport;
import com.vincedgy.jsf2project.jaxb.Ville;
import com.vincedgy.jsf2project.services.AgenceVoyagesServiceImpl;

@ManagedBean(name = "trajetBean")
@RequestScoped
public class TrajetBean implements Serializable {
	private static final long serialVersionUID = 1L;

	private String strDateDepart="";
	private String strDateRetour="";

	private List<String> modesChoisis;
	private List<String> villesChoisies;

	private List<ModeDeTransport> modesDeTransport;
	private List<Ville> villes;

	public TrajetBean() {
	}

	public List<String> getModesChoisis() {
		return modesChoisis;
	}

	public List<ModeDeTransport> getModesDeTransport() {
		return modesDeTransport;
	}

	public List<Ville> getVilles() {
		return villes;
	}

	public List<String> getVillesChoisies() {
		return villesChoisies;
	}

	public String submit() {
		villes = new ArrayList<Ville>();
		Iterator<Ville> listVilles = AgenceVoyagesServiceImpl.getInstance()
				.getAgenceVoyages().getVille().iterator();
		do {
			Ville ville = listVilles.next();
			for (String villeChoisie : villesChoisies) {
				if (ville.getCodePostal().equals(villeChoisie)) {
					villes.add(ville);
				}
			}
		} while (listVilles.hasNext());

		modesDeTransport = new ArrayList<ModeDeTransport>();
		Iterator<ModeDeTransport> listModes = AgenceVoyagesServiceImpl
				.getInstance().getAgenceVoyages().getModeDeTransport()
				.iterator();
		do {
			ModeDeTransport modeDeTransport = listModes.next();
			for (String modeChoisi : modesChoisis) {
				if (modeDeTransport.getIdentifiant().toString()
						.equals(modeChoisi)) {
					modesDeTransport.add(modeDeTransport);
				}
			}
		} while (listModes.hasNext());

		return "validate";
	}

	public void setModesChoisis(List<String> modesChoisis) {
		this.modesChoisis = modesChoisis;
	}

	public void setModesDeTransport(List<ModeDeTransport> modesDeTransport) {
		this.modesDeTransport = modesDeTransport;
	}

	public void setVilles(List<Ville> villes) {
		this.villes = villes;
	}

	public void setVillesChoisies(List<String> villesChoisies) {
		this.villesChoisies = villesChoisies;
	}

	public String getStrDateDepart() {
		return strDateDepart;
	}

	public void setStrDateDepart(String strDateDepart) {
		this.strDateDepart = strDateDepart;
	}

	public String getStrDateRetour() {
		return strDateRetour;
	}

	public void setStrDateRetour(String strDateRetour) {
		this.strDateRetour = strDateRetour;
	}

	public String getVerifDateDepart() {
		FacesContext context = FacesContext.getCurrentInstance();
		FacesMessage msg;		
		if ("".equals(strDateDepart) || strDateDepart == null) {
			msg = new FacesMessage("Date Départ","Date de départ invalide !");	
			msg.setSeverity(FacesMessage.SEVERITY_WARN);
			context.addMessage("dateDepartMsg", msg);
			return "La date de départ " + strDateDepart + " est invalide";
		} else {			
			return "La date de départ " + strDateDepart + " est valide";
		}
	}

	public String getVerifDateRetour() {
		FacesContext context = FacesContext.getCurrentInstance();
		FacesMessage msg;		
		if ("".equals(strDateRetour) || strDateRetour == null) {
			msg = new FacesMessage("Date Retour","Date de retour invalide !");	
			msg.setSeverity(FacesMessage.SEVERITY_WARN);
			context.addMessage("dateRetourMsg", msg);
			return "La date de retour " + strDateDepart + " est invalide";
		} else {
			return "La date de retour " + strDateRetour + " est valide";
		}
	}

}

src/main/webapp/AgenceReservation.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">
<h:body>
	<ui:composition template="/WEB-INF/templates/template.xhtml">

		<!-- 	<ui:define name="header"> -->
		<!-- 	    Add your header here or delete to use the default -->
		<!-- 	</ui:define> -->
		<ui:define name="content">
			
			<f:loadBundle basename="com.vincedgy.jsf2project.messages" var="msg" />
			<f:view>
				
				<h:messages globalOnly="true" rendered="true"/>
				
				<h:form id="myform">
					<h4>
						<h:outputLabel
							value="#{msg['login.form.welcome'] } #{loginBean.name }"></h:outputLabel>
					</h4>

					<h:panelGrid border="0" columns="2" style="width: 800px; ">
						<h:outputText value="#{msg['av.form.town']}" />

						<h:selectManyListbox size="5" style="width: 195px;"
							value="#{trajetBean.villesChoisies }"
							converter="#{villeConverter }">
							<f:selectItems value="#{agenceVoyageBean.villes }" var="ville"
								itemValue="#{ville.codePostal }" itemLabel="#{ville.nom }" />
						</h:selectManyListbox>


						<h:outputText value="#{msg['av.form.mode']}" />
						<h:selectManyCheckbox style="width: 116px; height: 107px; " styleClass="checkbox" selectedClass="selected"
							value="#{trajetBean.modesChoisis }">
							<br/><f:selectItems value="#{agenceVoyageBean.modesDeTransport }"
								var="mode" itemValue="#{mode.identifiant }"
								itemLabel="#{mode.nom }" />
							
						</h:selectManyCheckbox>

						<h:outputText value="#{msg['av.form.dateStart']}" />
						<h:panelGroup>
							<h:inputText value="#{trajetBean.strDateDepart }" id="dateDepart" />
							<h:outputText id="dateDepartVerifiee"
								value="#{trajetBean.verifDateDepart}" />
							<h:message for="dateDepart" id="dateDepartMsg" rendered="true"/>
						</h:panelGroup>

						<h:outputText value="#{msg['av.form.dateReturn']}" />
						<h:panelGroup>
							<h:inputText value="#{trajetBean.strDateRetour }" id="dateRetour" />
							<h:outputText id="dateRetourVerifiee"
								value="#{trajetBean.verifDateRetour}" />
							<h:message for="dateRetour" id="dateRetourMsg" rendered="true"/>
						</h:panelGroup>

						<f:facet name="footer">
							<h:commandButton value="#{msg['av.form.checkDate']}">
								<f:ajax execute="dateDepart" render="dateDepartVerifiee" />
								<f:ajax execute="dateRetour" render="dateRetourVerifiee" />
							</h:commandButton>
							<br />
							<h:commandButton value="#{msg['av.form.validate']}"
								action="#{trajetBean.submit }" />
						</f:facet>

					</h:panelGrid>

					<br />
					<h:commandLink action="login">
						<h:outputText value="Back to login"></h:outputText>
					</h:commandLink>
					<br />
				</h:form>
			</f:view>

		</ui:define>
		<!-- 	<ui:define name="footer"> -->
		<!-- 	    Add your footer here or delete to use the default -->
		<!-- 	</ui:define> -->
	</ui:composition>
</h:body>
</html>

src/main/webapp/ValidateReservation.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">
<h:body>
<ui:composition template="/WEB-INF/templates/template.xhtml">
	<!-- 	<ui:define name="header"> -->
	<!-- 	    Add your header here or delete to use the default -->
	<!-- 	</ui:define> -->
	<ui:define name="content">
		<f:loadBundle basename="com.vincedgy.jsf2project.messages" var="msg" />
		<f:view>
			<h:form>
				<h4>
					<h:outputLabel
						value="#{msg['login.form.welcome'] } #{loginBean.name }"></h:outputLabel>
				</h4>

				<h:panelGrid border="0" columns="2" styleClass="panelGridValid">
					<h:outputText value="#{msg['valid.form.listeVilles']}" />
					<h:panelGroup>
						<h:dataTable value="#{trajetBean.villes }" var="ville"
							styleClass="order-table" headerClass="order-table-header"
							rowClasses="order-table-odd-row,order-table-even-row"							
							onclick="alert('Click');
							">
							<h:column>
								<f:facet name="header">Nom</f:facet>
							 	#{ville.nom }
							</h:column>
							<h:column>
								<f:facet name="header">Code Postal</f:facet>
							 	#{ville.codePostal }
							</h:column>
						</h:dataTable>
					</h:panelGroup>
					<h:outputText value="#{msg['valid.form.listeModes']}" />
					<h:panelGroup>
						<h:dataTable value="#{trajetBean.modesDeTransport }" var="mode"
							styleClass="order-table" headerClass="order-table-header"
							rowClasses="order-table-odd-row,order-table-even-row"
							>
							<h:column>
								<f:facet name="header">Nom</f:facet>
							 	#{mode.nom }
							</h:column>
							<h:column>
								<f:facet name="header">Id</f:facet>
							 	#{mode.identifiant }
							</h:column>
						</h:dataTable>
					</h:panelGroup>
				</h:panelGrid>

				<br />
				<h:commandLink action="login">
					<h:outputText value="Back to login"></h:outputText>
				</h:commandLink>
				<br />
			</h:form>
		</f:view>

	</ui:define>
	<!-- 	<ui:define name="footer"> -->
	<!-- 	    Add your footer here or delete to use the default -->
	<!-- 	</ui:define> -->
</ui:composition>
</h:body>
</html>

src/main/webapp/WEB-INF/templates/footer.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">
<body>
	<ui:composition>		
		<footer style="float:right">
		<i>This is my footer</i>		
		</footer>
	</ui:composition>
</body>
</html>

src/main/webapp/WEB-INF/templates/header.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">
<body>
	<ui:composition>
		<header style="text-align: center">
			<h2>Votre agence de voyages</h2>
			<h:graphicImage value="resources/img/agenceVoyage_01.jpg" id="logo"/>
		</header>			
	</ui:composition>
</body>
</html>

src/main/webapp/WEB-INF/templates/template.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">
<h:head>
	
	<h:outputStylesheet name="libs/dojo/resources/dojo.css" />
	<h:outputStylesheet name="libs/dijit/themes/dijit.css" />
	<h:outputStylesheet name="libs/dijit/themes/tundra/tundra.css" />	
	<h:outputStylesheet name="css/style.css" />
	<h:outputStylesheet name="css/dataTables.css" />
	
	<h:outputScript>
		 dojoConfig = {
                has: {
                    "dojo-firebug": true
                },
                parseOnLoad: false,
                async: false
            }; 
	</h:outputScript>
	<h:outputScript name="libs/dojo/dojo.js" />
	
	
</h:head>
<h:body styleClass="tundra">

	<div id="header">
		<ui:insert name="header">
			<ui:include src="/WEB-INF/templates/header.xhtml" />
		</ui:insert>
	</div>

	<div id="content">

		<ui:insert name="content">
		</ui:insert>
	</div>

	<div id="footer">
		<ui:insert name="footer">
			<ui:include src="/WEB-INF/templates/footer.xhtml" />
		</ui:insert>
	</div>

</h:body>
</html>

src/main/webapp/login.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">
<h:body>
<ui:composition template="/WEB-INF/templates/template.xhtml">
	<!-- 	<ui:define name="header"> -->
	<!-- 	    Add your header here or delete to use the default -->
	<!-- 	</ui:define> -->
	<ui:define name="content">
				
		<f:loadBundle basename="com.vincedgy.jsf2project.messages" var="msg" />
		<f:view>			
			<h:form id="myform">
			 	<h3 style="width: 214px;">
					<h:outputLabel value="#{msg['login.form.title']}" rendered="true"></h:outputLabel>
				</h3>
				<h:panelGrid border="0" columns="3">
					<h:outputLabel value="#{msg['login.form.name'] }" rendered="true"></h:outputLabel>
					<h:inputText id="userName" value="#{loginBean.name }"></h:inputText>
					<h:message for="userName" style="color:red"></h:message>
					<h:outputLabel value="#{msg['login.form.password'] }" rendered="true"></h:outputLabel>
					<h:inputSecret id="password" value="#{loginBean.password }" required="true">
						<f:validator for="password" validatorId="ValidatePassword"/>
					</h:inputSecret>
					<h:message for="password" style="color:red"></h:message>									
				</h:panelGrid>				
				<br />
				<h:commandButton value="#{msg['login.form.login'] }" action="login"></h:commandButton>
			</h:form>
		</f:view>
	</ui:define>
	<!-- 	<ui:define name="footer"> -->
	<!-- 	    Add your footer here or delete to use the default -->
	<!-- 	</ui:define> -->
</ui:composition>
</h:body>
</html>

src/main/webapp/new.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">
<h:body>

	<ui:composition template="/WEB-INF/templates/template.xhtml">
		<!-- 	<ui:define name="header"> -->
		<!-- 	    Add your header here or delete to use the default -->
		<!-- 	</ui:define> -->
		<ui:define name="content">

			<h:outputScript>
				dojo.require("dojo.parser");
				dojo.require("dijit.form.ValidationTextBox");
				dojo.require("dijit.form.Textarea");
			    <!-- Recopie des champs de Dojo vers JSF-->
				function setDojoValue () {					
					return require(["dojo/dom","dojo/domReady!"], 
						function (dom) {
							var projectNameDojo = dom.byId("projectName");
							var projectNameJSF = projectNameDojo.previousElementSibling;
							projectNameJSF.value = projectNameDojo.value;
							var projectDescriptionDojo = dom.byId("projectDescription");
							var projectDescriptionJSF = projectDescriptionDojo.previousElementSibling;
							projectDescriptionJSF.value = projectDescriptionDojo.value;
							return;							
					});
				}				
			</h:outputScript>

			<f:loadBundle basename="com.vincedgy.jsf2project.messages" var="msg" />

			<f:view>
				<h:form id="myform">
					<h:panelGrid border="0" columns="2" style="width: 567px; ">

						<h:outputText value="#{msg['project.form.projectName']}" />
						<h:panelGroup>
							<h:inputHidden id="projectName"
								value="#{projectFormBean.projectName}" />
							<f:verbatim>
								<input type="text" name="projectName" id="projectName"
									data-dojo-type="dijit.form.ValidationTextBox" regExp="[\w]+"
									required="true" invalidMessage="Invalid project name" />
							</f:verbatim>

						</h:panelGroup>

						<h:outputText value="#{msg['project.form.projectDescription']}" />
						<h:panelGroup>
							<h:inputHidden id="projectDescription"
								value="#{projectFormBean.projectDescription}" />
							<f:verbatim>
								<textarea rows="2" cols="15" style="width: 80%"
									id="projectDescription" data-dojo-type="dijit.form.Textarea">
								</textarea>
							</f:verbatim>

						</h:panelGroup>
					</h:panelGrid>

					<br />
					<h:commandButton id="button_submit" action="success"
						value="#{msg['project.form.button'] }"
						onclick="setDojoValue(); return true;" type="submit"></h:commandButton>
				</h:form>

			</f:view>
		</ui:define>
		<!-- 	<ui:define name="footer"> -->
		<!-- 	    Add your footer here or delete to use the default -->
		<!-- 	</ui:define> -->
	</ui:composition>
</h:body>
</html>

src/main/webapp/new_bak.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">
<h:body>

	<ui:composition template="/WEB-INF/templates/template.xhtml">
		<!-- 	<ui:define name="header"> -->
		<!-- 	    Add your header here or delete to use the default -->
		<!-- 	</ui:define> -->
		<ui:define name="content">

			<f:loadBundle basename="com.vincedgy.jsf2project.messages" var="msg" />
			
			<f:view>
				<h:form id="myform">
					<h:panelGrid border="0" columns="2" style="width: 567px; ">
					
					<h:outputText value="#{msg['project.form.projectName']}" />
					<h:inputText id="projectName" value="#{projectFormBean.projectName}" size="5" style="width: 194px; "/>
					
					<h:outputText value="#{msg['project.form.projectDescription']}" />
					<h:inputTextarea id="projectDescription" value="#{projectFormBean.projectDescription}" rows="2" cols="15" style="height: 185px; width: 193px; "/>
					
					</h:panelGrid>
					
					<br />
					<h:commandButton id="button_submit" action="success" value="#{msg['project.form.button'] }" type="submit"></h:commandButton>					
				</h:form>
			
			</f:view>
		</ui:define>
		<!-- 	<ui:define name="footer"> -->
		<!-- 	    Add your footer here or delete to use the default -->
		<!-- 	</ui:define> -->
	</ui:composition>
</h:body>
</html>

src/main/webapp/project.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">
<h:body>
	
	<ui:composition template="/WEB-INF/templates/template.xhtml">
		<!-- 	<ui:define name="header"> -->
		<!-- 	    Add your header here or delete to use the default -->
		<!-- 	</ui:define> -->
		<ui:define name="content">

			<f:loadBundle basename="com.vincedgy.jsf2project.messages" var="msg" />

			<f:view>
				<h:form id="myform">
					<h:panelGrid border="0" columns="2" style="width: 567px; ">

						<h:outputText value="#{msg['project.form.projectName']}" />
						<h:outputText id="projectName"
							value="#{projectFormBean.projectName}" style="width: 194px; " />

						<h:outputText value="#{msg['project.form.projectDescription']}" />
						<h:outputText id="projectDescription"
							value="#{projectFormBean.projectDescription}" rerows="2"
							cols="15" style="height: 185px; width: 193px; " />

					</h:panelGrid>
					<h:commandLink action="newProject">
						<h:outputText value="#{msg['project.form.NewProject']}"></h:outputText>
					</h:commandLink>
					<br />
				</h:form>
			</f:view>
		</ui:define>
		<!-- 	<ui:define name="footer"> -->
		<!-- 	    Add your footer here or delete to use the default -->
		<!-- 	</ui:define> -->
	</ui:composition>
</h:body>
</html>